### ISSUE TITLE
Allow marking tickets as paid

### ISSUE THREAD

**Issue by Sohalt** [pretix/pretixdroid#34]
It would be cool to have the option to mark tickets which have not been paid yet as paid when scanning.
This would allow implementing a workflow for cash payments like in https://github.com/pc-coholic/de.pccoholic.pretix.cashpoint , i.e. someone buys a ticket with the https://github.com/pc-coholic/pretix-cashpayment or the "Manual payment" payment option, which then gets scanned, telling the person at the checkout that payment is still pending. They can then collect the payment in cash and mark the ticket as paid from the app.

**Comment by raphaelm** [comment]
(First of all, pretixdroid is not being developed any more, we'll be launching the successor pretixSCAN (already on GitHub) in a couple of weeks hopefully.)

Second, we're not planning to add this feature to pretixSCAN (or droid, for that matter). The reason is that it's problematic on a legal basis because pretixSCAN/pretixdroid do not fulfill the legal requirements of a system handling payments or money in many countries (and especially not in Germany, our home market). This is a feature that pretixPOS will get soon-ish, and workarounds like the (by this point probably a little old) cashpoint app and just doing it in the web backend exist for people who only need this occasinally.

**Comment by Sohalt** [comment]
Oh, cool. I didn't see pretixSCAN yet, looking forward to that.

For the second part, can you elaborate on the exact issues?
Is it, that pretixSCAN does not create an auditable trail? And that the customers don't get a receipt? I guess for the second case one could either automatically print a receipt or send one by email (because the email address is still saved with the order). I'm not sure if the email would be legal, but I'm assuming so, since online shops often also just send the payment confirmation/receipt by mail (but maybe there are different laws for cash payments). But then I've probably just described a large part of what distinguishes pretixPOS from pretixSCAN.

**Comment by raphaelm** [comment]
> Is it, that pretixSCAN does not create an auditable trail? 

Exactly that.

> And that the customers don't get a receipt?

That will be an issue by 2020 in Germany, yes, but the audit trail is the bigger issue.

> But then I've probably just described a large part of what distinguishes pretixPOS from pretixSCAN.

Well, yeah, handling cash is more tightly regulated than handling electronic sales since electronic money transfers already create a papertrail on their own. pretixPOS is mostly built to sell tickets which have not been purchaes before, but we'll rather add this feature over there as well since we already invest in all that regulation stuff there.
