### ISSUE TITLE
F-Droid Listing

### ISSUE THREAD

**Issue by IzzySoft** [pretix/pretixdroid#38]
I see you're deprecating this app in favor of its successor. Do you plan to bring the latter to F-Droid then as well?

**Comment by raphaelm** [comment]
We did not bring this app to F-Droid and we don't plan to bring the successor. If the F-Droid community wants to upload it, we support it, but we're not really fans of F-Droid from developer perspective. F-Droid re-builds and signs the binaries (for very good reasons!), which makes it impossible to supply customers with hotfixes on really urgent problems directly before an event. F-Droid is working to resolve these issues with reproducible builds and original signatures, but since they are low-staffed with volunteers, these things take a while.

**Comment by IzzySoft** [comment]
Thanks for your fast response! Indeed we are low-staffed (almost permanently, unfortunately). We'd wish things would look a bit better. Doing our best, but it's hard to catch up in so many places…

Thanks for supporting a listing! I'll then see to setup an RFP for it.

**Comment by IzzySoft** [comment]
PS, for reference: https://gitlab.com/fdroid/rfp/issues/1127
